### PR TITLE
Add simple HPCC Visualization Sample

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith gordonjsmith@gmail.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@richardkchapman Please Review

**Comment by richardkchapman** [comment]
Is any explanation / comments needed about what the various bits do and why?

@GordonSmith

**Comment by GordonSmith** [comment]
Probably - let me add a readme.md and some comments.

**Comment by GordonSmith** [comment]
@richardkchapman readme, comments and second example added.

**Pull request merged**
